small fix to regression and positive flows

diff --git a/.github/workflows/regression_testing.yaml b/.github/workflows/regression_testing.yaml
--- a/.github/workflows/regression_testing.yaml
+++ b/.github/workflows/regression_testing.yaml
@@ -43,16 +43,29 @@ jobs:
 
       - name: Run Tests
         run: |
+          id: run_tests
+          continue-on-error: true
           export BROWSER=chrome
           export GRID_URL=${{ github.event.inputs.grid_url }}
           
           mvn -q clean test -DsuiteXmlFile=testng-suites/testng-regression.xml
+          echo "exit_code=$?" >> $GITHUB_OUTPUT
 
       - name: Upload TestNG Report (HTML)
         uses: actions/upload-artifact@v4
         with:
           name: testng-report-ch
           path: target/surefire-reports/
+
+      - name: Mark job failed if tests failed
+        if: always()
+        run: |
+          if [ "${{ steps.run_tests.outputs.exit_code }}" != "0" ]; then
+            echo "Tests failed. Marking job as failed."
+            exit 1
+          else
+            echo "Tests passed."
+          fi
 
       - name: Tear down Grid
         run: docker stop grid_container || true
@@ -78,6 +91,8 @@ jobs:
 
       - name: Run Tests
         run: |
+          id: run_tests
+          continue-on-error: true
           export BROWSER=firefox
           export GRID_URL=${{ github.event.inputs.grid_url }}
           
@@ -88,6 +103,16 @@ jobs:
         with:
           name: testng-report-fx
           path: target/surefire-reports/
+
+      - name: Mark job failed if tests failed
+        if: always()
+        run: |
+          if [ "${{ steps.run_tests.outputs.exit_code }}" != "0" ]; then
+            echo "Tests failed. Marking job as failed."
+            exit 1
+          else
+            echo "Tests passed."
+          fi
 
       - name: Tear down Grid
         run: docker stop grid_container || true
